/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uts.pbo;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.lang.System.Logger;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.*;
import java.lang.System.Logger.Level;
import javax.swing.JOptionPane;
import uts.pbo.DbUtils;
/**
 *
 * @author IT GRC
 */
public class mahasiswa_uts extends javax.swing.JFrame {
    Connection conn;
    Statement stmt;
    PreparedStatement pstmt = null;

    String driver = "org.postgresql.Driver";
    String koneksi = "jdbc:postgresql://localhost:5432/UTS_PBO";
    String user = "postgres";
    String password = "123";
    InputStreamReader inputStreamReader = new InputStreamReader(System.in);
    BufferedReader input = new BufferedReader(inputStreamReader);


    /**
     * Creates new form mahasiswa_uts
     */
    public mahasiswa_uts() {
        initComponents();
        tampil();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtKodeMK = new javax.swing.JTextField();
        txtSKS = new javax.swing.JTextField();
        txtNamaMK = new javax.swing.JTextField();
        txtSmt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbTabelMK = new javax.swing.JTable();
        btnInsert = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MATA KULIAH");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Kode Mata Kuliah ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("SKS ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Nama Mata Kuliah ");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Semester Ajaran ");

        txtKodeMK.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtKodeMK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKodeMKActionPerformed(evt);
            }
        });

        txtSKS.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtSKS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSKSActionPerformed(evt);
            }
        });

        txtNamaMK.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        txtSmt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        tbTabelMK.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tbTabelMK.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbTabelMK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbTabelMKMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbTabelMK);

        btnInsert.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnInsert.setText("Insert");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btndelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btndelete.setText("Delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                                .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtKodeMK)
                            .addComponent(txtSKS)
                            .addComponent(txtNamaMK)
                            .addComponent(txtSmt)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(59, 59, 59)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtKodeMK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtSKS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNamaMK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSmt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate)
                    .addComponent(btnInsert)
                    .addComponent(btndelete)
                    .addComponent(btnClear))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtKodeMKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKodeMKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKodeMKActionPerformed

    private void txtSKSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSKSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSKSActionPerformed

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        String KodeMK, SKS, NamaMK, SemesterAjar;
        String hehe = txtKodeMK.getText();
        String hoho = txtSKS.getText();
        String huhu = txtNamaMK.getText();
        String hihi = txtSmt.getText();

        if (hehe.trim().isEmpty() && hoho.trim().isEmpty() && huhu.trim().isEmpty() && hihi.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "isi dulu yaa data Mata Kuliah nya! ");
        } else if (hehe.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "isi Kode Mata Kuliah dulu yaa! ");
        } else if (hoho.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "isi SKS anda dulu!");
        } else if (huhu.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "isi Nama Mata Kuliah dulu!");
        } else if (hihi.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "isi Semester Ajaran dulu!");
        } else {
            try {
                Class.forName(driver);
                conn = DriverManager.getConnection(koneksi, user, password);
                conn.setAutoCommit(false);

                String sql = "INSERT INTO MataKuliah VALUES(?,?,?,?)";
                pstmt = conn.prepareStatement(sql);

                KodeMK = txtKodeMK.getText();
                SKS = txtSKS.getText();
                NamaMK = txtNamaMK.getText();
                SemesterAjar = txtSmt.getText();

                pstmt.setString(1, KodeMK);
                pstmt.setLong(2, Long.parseLong(SKS));
                pstmt.setString(3, NamaMK);
                pstmt.setLong(4, Long.parseLong(SemesterAjar));
                
                pstmt.executeUpdate();

                JOptionPane.showMessageDialog(null, "data berhasil ditambahkan");
                conn.commit();// Commit transaksi setelah sejumlah operasi-insert berhasil
                pstmt.close();
                conn.close();

            } catch (ClassNotFoundException | SQLException ex) {
                JOptionPane.showMessageDialog(null, "terjadi kesalahan saat pengisian");
            }
        }
        bersih();
        tampil();                                             
    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        String KodeMK, SKSbaru, NamaMKbaru, SemesterAjarbaru;
        String hehe = txtKodeMK.getText();
        String hoho = txtSKS.getText();
        String huhu = txtNamaMK.getText();
        String hihi = txtSmt.getText();

        if (hehe.trim().isEmpty() && hoho.trim().isEmpty() && huhu.trim().isEmpty() && hihi.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "masukkan dulu data Mata Kuliah yang ingin diupdate! ");
        } else if (hehe.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "isi Kode Mata Kuliah dulu yaa! ");
        } else if (hoho.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "isi SKS yang ingin diupdate!");
        } else if (huhu.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "isi Nama Mata Kuliah dulu yang ingin diupdate!");
        } else if (hihi.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "isi Semester Ajaran dulu yang ingin diupdate!");
        } else {
            try {
                Class.forName(driver);
                String sql = "UPDATE MataKuliah SET SKS = ?, NamaMk = ?, SemesterAjar = ? WHERE KodeMK = ?";
                conn = DriverManager.getConnection(koneksi, user, password);
                pstmt = conn.prepareStatement(sql);

                KodeMK = txtKodeMK.getText();
                SKSbaru = txtSKS.getText();
                NamaMKbaru = txtNamaMK.getText();
                SemesterAjarbaru = txtSmt.getText();

                pstmt.setLong(1, Long.parseLong(SKSbaru));
                pstmt.setString(2, NamaMKbaru);
                pstmt.setLong(3, Long.parseLong(SemesterAjarbaru));
                pstmt.setString(4, KodeMK);
                
                int rowsAffected = pstmt.executeUpdate();
                if (rowsAffected > 0) {
                    JOptionPane.showMessageDialog(null, "data berhasil diupdate!");
                    pstmt.close();
                    conn.close();
                    bersih();
                } else {
                    JOptionPane.showMessageDialog(null, "data tidak ditemukan");
                }
            } catch (ClassNotFoundException | SQLException ex) {
            }
            tampil();
        }                                           
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        String KodeMK;
        String hehe = txtKodeMK.getText();

        if (hehe.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "masukkan dulu data Mata Kuliah yang ingin dihapus!");
        } else {
            try {
                Class.forName(driver);
                conn = DriverManager.getConnection(koneksi, user, password);

                int jawab = JOptionPane.showConfirmDialog(null, "Silakan Konfirmasi?");
                switch (jawab) {
                    case JOptionPane.YES_OPTION:
                        String sql = "DELETE FROM MataKuliah WHERE KodeMK = ?";
                        pstmt = conn.prepareStatement(sql);

                        KodeMK = txtKodeMK.getText();
                        pstmt.setString(1, KodeMK);
                        pstmt.executeUpdate();

                        pstmt.close();
                        conn.close();
                        bersih();
                        break;

                    case JOptionPane.NO_OPTION:
                        JOptionPane.showMessageDialog(this, "anda menjawab tidak");
                        break;
                }

            } catch (ClassNotFoundException | SQLException ex) {
                System.out.println("terjadi kesalahan saat melakukan operasi insert dalam loop.");
                ex.printStackTrace();
                try {
                    if (conn != null) {
                        conn.rollback();
                    }
                } catch (SQLException e) {
                    System.out.println("Gagal melakukan rollback transaksi.");
                    e.printStackTrace();
                }
            }
            tampil();
        }            
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        bersih();
    }//GEN-LAST:event_btnClearActionPerformed

    private void tbTabelMKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbTabelMKMouseClicked
        int row = tbTabelMK.getSelectedRow();
        txtKodeMK.setText(tbTabelMK.getValueAt(row, 0).toString());
        txtSKS.setText(tbTabelMK.getValueAt(row, 1).toString());
        txtNamaMK.setText(tbTabelMK.getValueAt(row, 2).toString());
        txtSmt.setText(tbTabelMK.getValueAt(row, 3).toString());
    }//GEN-LAST:event_tbTabelMKMouseClicked

     public void tampil() {
        try {
            // TODO code application logi
            Class.forName(driver);
            String sql = "SELECT * FROM MataKuliah ";
            conn = DriverManager.getConnection(koneksi, user, password);
            stmt = conn.createStatement();

            while (!conn.isClosed()) {

                ResultSet rs = stmt.executeQuery(sql);
                this.tbTabelMK.setModel(DbUtils.resultSetToTableModel(rs));
                while (rs.next()) {
                    System.out.println(String.valueOf(rs.getObject(1)) + " " + String.valueOf(rs.getObject(2)) + " " + String.valueOf(rs.getObject(3)) + " " + String.valueOf(rs.getObject(4)));
                }
                conn.close();
            }

            stmt.close();

        } catch (ClassNotFoundException | SQLException ex) {
             java.util.logging.Logger.getLogger(mahasiswa_uts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    public void bersih() {
        txtKodeMK.setText("");
        txtSKS.setText("");
        txtNamaMK.setText("");
        txtSmt.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mahasiswa_uts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mahasiswa_uts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mahasiswa_uts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mahasiswa_uts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mahasiswa_uts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btndelete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbTabelMK;
    private javax.swing.JTextField txtKodeMK;
    private javax.swing.JTextField txtNamaMK;
    private javax.swing.JTextField txtSKS;
    private javax.swing.JTextField txtSmt;
    // End of variables declaration//GEN-END:variables
}
